-- Run after schema.sql.
-- This file seeds starter connector templates that every user can copy into their own registry.

insert into connector_registry (
  owner_user_id,
  connector_name,
  connector_family,
  connector_type,
  status,
  connected_service,
  supported_actions,
  input_requirements,
  confirmation_policy,
  permission_scope,
  execution_boundary,
  fallback_path,
  last_verified,
  notes,
  truthful_band,
  is_template
) values
(
  null,
  'Native Workspace Tools',
  'Native',
  'Built-in',
  'active_connected',
  'Current workspace',
  '["Planning","Code generation","Knowledge organization","Artifacts"]'::jsonb,
  '["Prompt","Uploaded files"]'::jsonb,
  'Normal confirmation for destructive edits only.',
  'Current session only',
  'Direct in-session execution',
  'None required',
  current_date,
  'Starter template: always truthful, always visible.',
  'direct',
  true
),
(
  null,
  'Calendar / Task / Notes',
  'Productivity',
  'External connector',
  'available_but_unconfigured',
  'Not configured',
  '["Create calendar event","Create task","Append notes"]'::jsonb,
  '["Verified credentials","Required fields","Approval"]'::jsonb,
  'Explicit confirmation for write actions.',
  'Provider-specific',
  'Connector execution only after setup',
  'Generate Action Pack',
  current_date,
  'Starter template only.',
  'connector',
  true
),
(
  null,
  'Builder / Deployment',
  'Engineering',
  'External connector',
  'available_but_unconfigured',
  'Not configured',
  '["Create preview deploy","Create repo","Update env vars"]'::jsonb,
  '["Platform access","Repo access","Approval"]'::jsonb,
  'Explicit confirmation for irreversible changes.',
  'Provider-specific',
  'Connector or handoff only',
  'Provide deployment runbook',
  current_date,
  'Starter template only.',
  'connector',
  true
),
(
  null,
  'External AI Provider Handoff',
  'AI',
  'Handoff',
  'handoff_only',
  'Manual handoff',
  '["Prompt transfer","Model comparison","Manual evaluation"]'::jsonb,
  '["Prompt pack","Manual execution"]'::jsonb,
  'Manual only',
  'No direct access',
  'Handoff-ready only',
  'Copy-ready prompt pack',
  current_date,
  'Starter template only.',
  'handoff',
  true
)
on conflict do nothing;
